[build]
command = "npm install --include=dev && npx prisma generate && npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18.19.0"
NODE_ENV = "development"
NPM_FLAGS = "--legacy-peer-deps --prefer-offline"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
