[build]
command = "npm install && npx prisma generate && npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18.19.0"
NODE_ENV = "production"
NEXT_USE_NETLIFY_EDGE = "true"
NEXT_FORCE_EDGE_IMAGES = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
